### ISSUE TITLE
automatically create `build/entries/` to avoid an ENOENT and 500 error

### ISSUE THREAD

**Issue by Rhinozz** [m4rch3n1ng/blictionary#2]
upon building and running without creating the `entries` directory, an ENOENT error is thrown and svelte shows a 500 Internal Error on the site; creating the folder prevents the error and shows the UI.

**Comment by m4rch3n1ng** [comment]
thought about how to do this and i'm not quite sure. i think there are basically three ways to achieve this and none of them are perfect:

1. every time the server looks for the entry files, it also looks if the directory exists. this is redundant after the first time
1. it only checks on the initial launch. there is a way [to achieve this](https://kit.svelte.dev/docs/adapter-node#custom-server), but it's less than ideal, especially for such a small check
1. i add a post-build script, that checks if the directory exists and if it doesn't it creates one in `builds/`. the drawback is that this way it only works if you use the `cd builds/ && node .` version but i think that it's still the best solution to this

**Comment by Mg138** [comment]
Just do mkdirs (if TS has a way to call that) before accessing it?

**Comment by Mg138** [comment]
mkdirs makes the required directory recursively and usually doesn't error if they already exist

**Comment by m4rch3n1ng** [comment]
afaik node doesn't have mkdirs directly, but it has `existsSync` and `await mkdir(p, { recursive: true })`, which do the same thing, but like i said, i think that that is unnecessary to do every time. i'll need a post-build script anyways so i'll make it in that step then.
