### ISSUE TITLE
add support for sub-entries ("compounds" in the OED)

### ISSUE THREAD

**Issue by Rhinozz** [m4rch3n1ng/blictionary#9]
![image](https://user-images.githubusercontent.com/68926744/222979733-1d5c0d59-8b8e-4636-b7b9-8c5df4f93af7.png)

```ts
export interface SubEntry {
	word: string
	class: string | string[]
	definition: string
	quotes?: Quote[]
}
```

you may also want to use the `Definition` interface, but i'm not sure how that's implemented right now

**Comment by m4rch3n1ng** [comment]
ref https://www.oed.com/view/Entry/14903#eid29096738
